### PR TITLE
Add html improvements to changelog

### PR DESCRIPTION
**Pull request by tgoettlicher**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 38d622f2f349f1d7cda4ede3bd0bfb4b51873550 into b5378167cbc5d7dc02bc09dfedc4155d6c542f2a )

**Comment by aduffeck** [comment]
lgtm

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 38d622f2f349f1d7cda4ede3bd0bfb4b51873550 into 5ce35a8b629190d5e9c742cd1b42340916de11ba )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 38d622f2f349f1d7cda4ede3bd0bfb4b51873550 into 705c4ff52b00d00b6668e59d516c0c1d26a5e5fa )

**Pull request merged**
