### PR TITLE
Raise during Kiwi export if there is no usable repository

### PR DESCRIPTION
**Pull request by thardeck**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://ci.opensuse.org/job/machinery-prophet/20171/console
If the given link has expired, you can force a Prophet rerun by just deleting this comment.
( Failure: Merged 2c649ec3306479777bf6a44eaf6ca7ad9b77be3b into b418c745c51e142d9cd706cf5a60753b7fc2102f )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged fe92f8a525db8bfa82bc7f9745824a48316f6e5a into b418c745c51e142d9cd706cf5a60753b7fc2102f )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing. (Merged fe92f8a525db8bfa82bc7f9745824a48316f6e5a into b418c745c51e142d9cd706cf5a60753b7fc2102f)

**Comment by tgoettlicher** [comment]
LGTM. Please close https://github.com/SUSE/machinery/issues/617 when you merge it.

**Comment by thardeck** [comment]
I will merge #625 instead which consist these changes.

**Pull request closed without merging**
