### PR TITLE
Fix `machinery remove` task

### PR DESCRIPTION
**Pull request by Werni**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged ba2deca99391b2f0aa8cff4d427bb8d3a115197d into 070b66eb20efd1514313c5c84866a2c827f1a43a )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 01a53e64a9389c0a7522e09ad712396a4fe247a7 into 070b66eb20efd1514313c5c84866a2c827f1a43a )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 79537719f7a4180776558b4f0f292f358629cd78 into 070b66eb20efd1514313c5c84866a2c827f1a43a )

**Comment by cornelius** [comment]
lgtm

**Pull request merged**
