### PR TITLE
Make schema validation errors as warnings

### PR DESCRIPTION
**Pull request by Werni**
Superseeds #526

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d3c3b375170d24eabe23927583ff448de2bde054 into d5126d6c5c772df1d54b3c9f95f153c998c35299 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 2fdcfb616578dd572e49e2f5fb69b9654a22d671 into d5126d6c5c772df1d54b3c9f95f153c998c35299 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d71ca52b8b95983bb5237aa2910c243e51050cc7 into d5126d6c5c772df1d54b3c9f95f153c998c35299 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 8356eabe80ce3aacedb333d244ab1e29d539333a into d5126d6c5c772df1d54b3c9f95f153c998c35299 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 8356eabe80ce3aacedb333d244ab1e29d539333a into d0c0080040fc28087d7e699ff6218a6fddecf9c6 )

**Comment by cornelius** [comment]
The commit message should be "Make schema validation errors warnings" or "Treat schema validation errors as warnings"

**Comment by cornelius** [comment]
This change causes a lot of backup description to be created. On each call of `upgrade-format` a backup is added. One thing which needs to be fixed is that the backup is only created when an upgrade is actually executed. The other thing is that backup descriptions probably should not be visible to users in the same way as all the others. Does it really make sense to have them on the same level as all other descriptions?

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 8356eabe80ce3aacedb333d244ab1e29d539333a into eb41dec50a46ac11a329f11cbd24960f9ca6b0f2 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 8356eabe80ce3aacedb333d244ab1e29d539333a into a14722a01fe7f4f49854a1fef648e164bf18ade3 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 8356eabe80ce3aacedb333d244ab1e29d539333a into 4d75214a7046c2f351c267d7b11cec2cfc38366c )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 8356eabe80ce3aacedb333d244ab1e29d539333a into 2f9d57695b44ae5634e55ebbeb93084693f4a9fd )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 8356eabe80ce3aacedb333d244ab1e29d539333a into 9f70f8578b2f9e7731b804e522b915700f7ce127 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 8356eabe80ce3aacedb333d244ab1e29d539333a into f07b7119c8f1bf2f8438a8048097f531577b1bb8 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 9393ee5e0bde39a505a17ae446e06094b9719be3 into f07b7119c8f1bf2f8438a8048097f531577b1bb8 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 4b88ba96ccb595d5c01895a376e93422f60f5824 into f07b7119c8f1bf2f8438a8048097f531577b1bb8 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged bf8e14e2c2eabae27160d4f69903466601a4a4ee into f07b7119c8f1bf2f8438a8048097f531577b1bb8 )

**Comment by cornelius** [comment]
The patch looks good to me now.

**Pull request merged**
