### PR TITLE
Raise error if port is already in use

### LINKED ISSUE #1153: Handle error in `machinery serv` if port is already in use
```
machinery serv host
The description is now available at http://127.0.0.1:7585/host

The web server can be closed with Ctrl+C.

Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/lib64/ruby/2.1.0/socket.rb:206:in `bind': Address already in use - bind(2) for 127.0.0.1:7585 (Errno::EADDRINUSE)
        from /usr/lib64/ruby/2.1.0/socket.rb:206:in `listen'
        from /usr/lib64/ruby/2.1.0/socket.rb:461:in `block in tcp_server_sockets'
        from /usr/lib64/ruby/2.1.0/socket.rb:232:in `each'
        from /usr/lib64/ruby/2.1.0/socket.rb:232:in `foreach'
        from /usr/lib64/ruby/2.1.0/socket.rb:459:in `tcp_server_sockets'
        from /usr/lib64/ruby/2.1.0/webrick/utils.rb:75:in `create_listeners'
        from /usr/lib64/ruby/2.1.0/webrick/server.rb:132:in `listen'
        from /usr/lib64/ruby/2.1.0/webrick/server.rb:113:in `initialize'
        from /usr/lib64/ruby/2.1.0/webrick/httpserver.rb:45:in `initialize'
        from /usr/lib64/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:31:in `new'
        from /usr/lib64/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:31:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1505:in `start_server'
        from /usr/lib64/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1443:in `run!'
        from /data/machinery/lib/html.rb:208:in `block in run_server'
```

### PR DESCRIPTION
**Pull request by vwallfahrer**
Superseds #1167 
Fixes #1153

### CODE REVIEW

**Comment by tgoettlicher** [comment]
If there is a server already running and the user runs `machinery show foobar --html` the web browser window pops up and disguises the error message.

**Comment by thardeck** [comment]
The problem is, that it still starts the browser.

**Comment by thardeck** [comment]
Doesn't work for me. It still opens another tab.

**Comment by mauromorales** [comment]
@keberle94 I think what you wanted to do was to configure the Thread::abort_on_exception = true

**Comment by thardeck** [comment]
lgtm

**Comment by keberle94** [comment]
Squashed by #1173

**Pull request closed without merging**
