### PR TITLE
Encapsulate Machinery classes in the Machinery module namespace

### PR DESCRIPTION
**Pull request by bear454**
Resolves https://github.com/SUSE/machinery/issues/2170 by encapsulating all Machinery classes in the `Machinery::` module.

Bonus: UI-specific code is namespaced in `Machinery::Ui::`.

### CODE REVIEW

**Comment by bear454** [comment]
Rubocop reports `2092 offenses` and @houndci-bot won't give me a complete list of it's complaints... just adds more comments after each fix. How am I supposed to get the style in shape?

**Comment by thardeck** [comment]
@bear454 Thx for your pr. You could use the rubocop-git extension on your changes before committing them.

**Comment by bear454** [comment]
@thardeck this is as far as I'm willing to go, wrt to style guide. Making any more changes would be too intrusive on the codebase, considering the sum total of change here is to prefix with the `Machinery::` module name, and in a few cases, some indenting.

**Comment by thardeck** [comment]
Superseded by #2202

**Pull request closed without merging**
