### PR TITLE
Clean up buildtask spec

### PR DESCRIPTION
**Pull request by thardeck**
Refers to pr #617 and bases on #624

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 7508e5ab825ef388d543d9b1636e5643277557ce into b418c745c51e142d9cd706cf5a60753b7fc2102f )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://ci.opensuse.org/job/machinery-prophet/24024/console
If the given link has expired, you can force a Prophet rerun by just deleting this comment. (Merged 7508e5ab825ef388d543d9b1636e5643277557ce into b418c745c51e142d9cd706cf5a60753b7fc2102f)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://ci.opensuse.org/job/machinery-prophet/24041/console
If the given link has expired, you can force a Prophet rerun by just deleting this comment. (Merged 7edfc8d2e9c1119c3e77f43555b4afbd8cb61f91 into b418c745c51e142d9cd706cf5a60753b7fc2102f)

**Comment by thardeck** [comment]
This pr can be ignored for now

**Comment by aduffeck** [comment]
lgtm

**Pull request merged**
