### PR TITLE
Add has_command method to system

### PR DESCRIPTION
**Pull request by Werni**
This method returns true if the system to inspect has the given
command else it will return false.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged c86a268bfa237eb69b26119c19e07dd14284921f into 50806d9ec88d48511f31c5efd67d677e13e71072 )

**Comment by thardeck** [comment]
lgtm

**Comment by thardeck** [comment]
I think the method is confusing. It doesn't just test if the command exists, it also runs it which is a problem imho because it can return a value unequal zero which would look like a non existing command.

**Comment by thardeck** [comment]
I would use `type -p <command>` instead which is similar to `which` but should exist on all distributions.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d23d8a9bf8ef88f9154006172c7df29b8f975cfb into 50806d9ec88d48511f31c5efd67d677e13e71072 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged e4690d4597a5f70f358badc8ee5468468651aa4f into 50806d9ec88d48511f31c5efd67d677e13e71072 )

**Comment by tgoettlicher** [comment]
There is also a has_command? method in my open pull request https://github.com/SUSE/machinery/pull/525 . It also checks if the commands work with specific arguments. That's needed by the services inspector to figure out if it's a SUSE or Red Hat system.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 2575f0e8321f0dd17bf9ae17c652844cfdbc183d into 50806d9ec88d48511f31c5efd67d677e13e71072 )

**Comment by thardeck** [comment]
But I think this implementation was wrong, like I mentioned in my commands. I would prefer Ricks implementation and if the has_command is true, then use run_command to actually run the command.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 2dab0147a8fbd400f0b041ce6374a58b0af8690e into 50806d9ec88d48511f31c5efd67d677e13e71072 )

**Comment by cornelius** [comment]
I agree with @thardeck. The implementation using `type` is more correct as it doesn't have side effects.

Patch looks good to me.

**Pull request merged**
