### PR TITLE
Fix support non host analyze archs

### PR DESCRIPTION
**Pull request by Werni**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 52d92d9aa34b6313239039bf1a23d2160083ab9e into 7179ec894701e9d20ec9c290a6f9297b85c9f994 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged bf5fd4bf31f15bd2ed97637b5d3cd1e8789f8c30 into 7179ec894701e9d20ec9c290a6f9297b85c9f994 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged bf5fd4bf31f15bd2ed97637b5d3cd1e8789f8c30 into 1e20fe81a10a2ed1662a4c16b427eef09df8a514 )

**Comment by aduffeck** [comment]
lgtm besides the nitpick.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d91ea63e914ed927d4c6574a6bbb93bbf5b878f4 into 1e20fe81a10a2ed1662a4c16b427eef09df8a514 )

**Pull request closed without merging**
