### PR TITLE
[Review] Request from 'aduffeck' @ 'SUSE/machinery/review_150112_update_news_file'

### PR DESCRIPTION
**Pull request by aduffeck**
Please review the following changes:
  * c2f8287 Mention s390 support in NEWS file

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged c2f828798e5c35745a3265c376259c4daa9d2174 into db2dd3860bcc9d23b1381752d135976d4dafa658 )

**Comment by tgoettlicher** [comment]
lgtm

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged c2f828798e5c35745a3265c376259c4daa9d2174 into d9b78a9ef46c7184aded6fbcca9e5066aefde7cc )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged c2f828798e5c35745a3265c376259c4daa9d2174 into ac34cdec74c5bcd630d09119c29f7f4a0e3ebd44 )

**Pull request merged**
