### PR TITLE
[Review] Request from 'tgoettlicher' @ 'SUSE/machinery/review_150217_use_backwards_compatible_stat_command_options'

### PR DESCRIPTION
**Pull request by tgoettlicher**
Please review the following changes:
  * d671ae6 Use backwards compatible stat command options
  * 62795eb Merge pull request #605 from SUSE/clean_up_patterns_inspector
  * de7be58 Clean up patterns inspector

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d671ae67db52418bd54bb6e48b10051a1cad3a66 into 62795eb5dcafbbe53ab0c0e34ac1887cad111be6 )

**Comment by aduffeck** [comment]
lgtm

**Comment by tgoettlicher** [comment]
This pull request contains fixes to make the inspection of RHEL4 work. It's not complete for all scopes, yet.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d671ae67db52418bd54bb6e48b10051a1cad3a66 into b0add9225d577595e4a33a9c5cd600f2c54cbf79 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d671ae67db52418bd54bb6e48b10051a1cad3a66 into 3a3d4ff91661311b1b978d83193ff511c2e6a974 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d671ae67db52418bd54bb6e48b10051a1cad3a66 into 29e8876cf2000878478dc1bc3e687efbdbfd153c )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d671ae67db52418bd54bb6e48b10051a1cad3a66 into 00f91dfd09bfbbba0c48cc84da9ec0dc129878a6 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d671ae67db52418bd54bb6e48b10051a1cad3a66 into 5ef7ba8492b6f5ae90e6646ce6e54a52f67fe680 )

**Comment by thardeck** [comment]
integration tests went through fine

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d671ae67db52418bd54bb6e48b10051a1cad3a66 into b418c745c51e142d9cd706cf5a60753b7fc2102f )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing. (Merged d671ae67db52418bd54bb6e48b10051a1cad3a66 into b418c745c51e142d9cd706cf5a60753b7fc2102f)

**Comment by thardeck** [comment]
Closing this for now since it only fixes one part of the issue.

**Pull request closed without merging**
