### PR TITLE
Fix empty repositories

### LINKED ISSUE #536: Machinery inspection fails when no repository is present
Tested platforms: SLE 12 (x86_64 and PPC)

```

machinery inspect  -x 192.168.100.111
```
Inspecting 192.168.100.111 for groups, config-files, os, changed-managed-files, patterns, packages, repositories, unmanaged-files, services, users...
Inspecting groups...
 -> Found 50 groups.
Inspecting config-files...

 -> Extracted 15 changed configuration files.
Inspecting os...
 -> Found operating system 'SUSE Linux Enterprise Server 12' version '12'.
Inspecting changed-managed-files...
 -> Extracted 31 changed files.
Inspecting patterns...
 -> Found 12 patterns.
Inspecting packages...
 -> Found 1592 packages.
Inspecting repositories...
Machinery experienced an unexpected error. Please file a bug report at https://github.com/SUSE/machinery/issues/new.
Execution of "ssh root@192.168.100.111 LC_ALL\=C zypper --non-interactive repos --details" failed with status 6 (no error output).

**Standard output:**
**Warning: No repositories defined.**
**Use the 'zypper addrepo' command to add one or more repositories.**

```
Backtrace:
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/bundle/ruby/2.0.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/bundle/ruby/2.0.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/lib/remote_system.rb:73:in `run_command'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/plugins/inspect/repositories_inspector.rb:27:in `inspect'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/lib/inspect_task.rb:78:in `block in build_description'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/lib/inspect_task.rb:75:in `each'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/lib/inspect_task.rb:75:in `build_description'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/lib/inspect_task.rb:23:in `inspect_system'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/lib/cli.rb:459:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150119T194825ZopenSUSE131gitd5126d6/bin/machinery:26:in `<top (required)>'
/usr/bin/machinery:26:in `load'
/usr/bin/machinery:26:in `<main>'

```

### PR DESCRIPTION
**Pull request by cornelius**
Fixes #536

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged f1a80a73e4be94f0075db727504d9d4729f9d8ac into eb41dec50a46ac11a329f11cbd24960f9ca6b0f2 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged ae2ecbc64b6aaffbce324413c60eca30148e4393 into eb41dec50a46ac11a329f11cbd24960f9ca6b0f2 )

**Comment by tgoettlicher** [comment]
lgtm

**Comment by cornelius** [comment]
Thomas says it looks good now.

**Pull request merged**
