### PR TITLE
Add table of contents to developer documentation

### PR DESCRIPTION
**Pull request by mschnitzer**
Live: https://github.com/SUSE/machinery/blob/update_dev_readme/docs/README.md

### CODE REVIEW

**Comment by cornelius** [comment]
Could you do this in markdown instead of html? Would make it easier to read and edit.

**Comment by mschnitzer** [comment]
Will do.

**Comment by mschnitzer** [comment]
@cornelius What do you think about this? https://github.com/SUSE/machinery/blob/7963746d1d909a70d9cf79bbee100e0a44ff6db0/docs/README.md

**Comment by cornelius** [comment]
lgtm

**Pull request merged**
