### PR TITLE
Added supported architectures to man pages

### PR DESCRIPTION
**Pull request by tgoettlicher**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 5fab28735071b5992b2888a87cadaadbe005e877 into 3fd168162fd8397623ff865175442ee8758c99b9 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 5fab28735071b5992b2888a87cadaadbe005e877 into c0ce4bd87fdabb0641991a694d820d142bfd60bb )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 5fab28735071b5992b2888a87cadaadbe005e877 into 352a3609e43d25bf21f5879fbe55a5203270543a )

**Comment by thardeck** [comment]
lgtm but shouldn't we add "only" to the sentence?

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 5fab28735071b5992b2888a87cadaadbe005e877 into 1039244745d666eb0aa31ebdcf8fd9e5c5cc6936 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 39e93e18c39e3ad3b49a30a4c461f7eb1f489c02 into 1039244745d666eb0aa31ebdcf8fd9e5c5cc6936 )

**Comment by thardeck** [comment]
lgtm

**Pull request merged**
