### PR TITLE
Adapt prophet config to the new status based tracking approach

### PR DESCRIPTION
**Pull request by aduffeck**
See https://github.com/b4mboo/prophet/pull/10 for more details.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 719c5f6b3fbeb9ebaa1bffb1aceae0d4a6956011 into b418c745c51e142d9cd706cf5a60753b7fc2102f )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing. (Merged 719c5f6b3fbeb9ebaa1bffb1aceae0d4a6956011 into b418c745c51e142d9cd706cf5a60753b7fc2102f)

**Comment by thardeck** [comment]
I suppose config.comment_failure could be removed then too?

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing. (Merged 142e3c5fd81709cf3c213681756e78f7b9220f64 into b418c745c51e142d9cd706cf5a60753b7fc2102f)

**Comment by thardeck** [comment]
I am unable to test it so I am not sure but it looks good to me.

**Pull request merged**
