### PR TITLE
Changed attribute name from packagemanager to package_manager

### PR DESCRIPTION
**Pull request by tgoettlicher**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 0a4ae70fd0c364c2e7924bc71e095c47de99b1a1 into 8625ec200dfeb1404e9c03e1714e85de0f7bec6a )

**Comment by thardeck** [comment]
conclusion wasn't updated. No new commit needed. LGTM besides that.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d3bb5bc1af2459f4162b781a9345a7f779e4c4e6 into 8625ec200dfeb1404e9c03e1714e85de0f7bec6a )

**Comment by thardeck** [comment]
lgtm

**Pull request merged**
