### PR TITLE
[Review] Request from 'aduffeck' @ 'SUSE/machinery/review_150217_report_validation_errors_during_upgrade_format_force_'

### PR DESCRIPTION
**Pull request by aduffeck**
Please review the following changes:
  * 83a4fb2 Report validation errors during "upgrade-format --force"
  * 18321cf Add missing test dependency on ruby-libvirt

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 83a4fb2d4d76a9ce4a4a064c55040bb26049d68c into 005e5c6d8aeaa553ada500f06ee7d09a08f836e0 )

**Comment by thardeck** [comment]
lgtm besides the comment

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 83a4fb2d4d76a9ce4a4a064c55040bb26049d68c into 9ff5771b4ae98c1d5d99fdfcaf200ca578f29f22 )

**Comment by aduffeck** [comment]
merged

**Pull request closed without merging**
