### PR TITLE
Optimize list loading

### PR DESCRIPTION
**Pull request by thardeck**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://ci.opensuse.org/job/machinery-prophet/8685/console
If the given link has expired, you can force a Prophet rerun by just deleting this comment.
( Failure: Merged f38fb004c80101d5d3b4011486add295dd37de90 into 333011a35059c8bbcb8299d70f931adb30f4c2f9 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged ee64644df6aea8a57f2b12d3181eb382f7793985 into 333011a35059c8bbcb8299d70f931adb30f4c2f9 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 2b5fcc0ee3d91f15af011387a9a0676c3daed523 into 333011a35059c8bbcb8299d70f931adb30f4c2f9 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 95dff7a092dfa803f47ddf0dbafd7571d8bdaa10 into 333011a35059c8bbcb8299d70f931adb30f4c2f9 )

**Comment by cornelius** [comment]
The speedup is great :clap: 

I'm not sure that it's the right way to use the Manifest instead of the SystemDescription. The ListTask class then depends on internal knowledge, e.g. how to get the path to the manifest.

Maybe it would be better to decouple the loading of the system description from the validation, so that it can explicitly called and disabled, depending on the use case.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 95dff7a092dfa803f47ddf0dbafd7571d8bdaa10 into 5837eb4b77c818409e20d919310f35e217a91b09 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 95dff7a092dfa803f47ddf0dbafd7571d8bdaa10 into 0fcedff80dc11f696cb3236f26aae0c4fba6baaf )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 95dff7a092dfa803f47ddf0dbafd7571d8bdaa10 into b5378167cbc5d7dc02bc09dfedc4155d6c542f2a )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 95dff7a092dfa803f47ddf0dbafd7571d8bdaa10 into 5ce35a8b629190d5e9c742cd1b42340916de11ba )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 95dff7a092dfa803f47ddf0dbafd7571d8bdaa10 into 705c4ff52b00d00b6668e59d516c0c1d26a5e5fa )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 95dff7a092dfa803f47ddf0dbafd7571d8bdaa10 into b94bcdbf17145fccab16c76b11872884be1fcea4 )

**Pull request closed without merging**
