### PR TITLE
Test

### PR DESCRIPTION
**Pull request by alfredtestuser**

### CODE REVIEW

**Comment by opensusegithubapi** [comment]
Can one of the admins verify this patch?

**Comment by opensusegithubapi** [comment]
Can one of the admins verify this patch?

**Comment by alfredtestuser** [comment]
retest this please

**Comment by thardeck** [comment]
retest this please

**Comment by alfredtestuser** [comment]
retest this please

**Comment by thardeck** [comment]
retest this please

**Pull request closed without merging**
