### PR TITLE
Do not read real machinery config during test

### PR DESCRIPTION
**Pull request by aduffeck**

### CODE REVIEW

**Comment by aduffeck** [comment]
RBR branch for #706 which doesn't rely on FakeFS

**Comment by thardeck** [comment]
Thx, but I am not sure if this is better. It is a lot of more stubbing and changing so I leave both there until someone else decides.

**Comment by aduffeck** [comment]
Not sure what you mean, it's the same amount of stubbing as before and as
in your branch, just on a higher level where it makes more sense. It's a
cleaner fix than resetting the config by throwing FakeFS at it although the
actual data is still being stubbed imo.
Am 13.03.2015 16:52 schrieb "Tim Hardeck" <notifications@github.com>:

**Comment by thardeck** [comment]
lgtm

**Pull request merged**
