### PR TITLE
Refactor migration

### PR DESCRIPTION
**Pull request by Werni**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged f006a789cf2644c714c7bddf72d0195d9d08a620 into 5960b08e05ca243e863d7e95313d893a69f27536 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 0ec9933d127c2b60a33f3570fe13857d1fb94eaf into 5960b08e05ca243e863d7e95313d893a69f27536 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 0ec9933d127c2b60a33f3570fe13857d1fb94eaf into b84e426d717244615b9c983a03284137c17411e1 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 0ec9933d127c2b60a33f3570fe13857d1fb94eaf into 12a9cbb125e9d1ee3a7479b949f94036f389424a )

**Comment by cornelius** [comment]
lgtm

**Pull request merged**
