### PR TITLE
Fix error messages when build, deploy, or export to kiwi is not supported

### PR DESCRIPTION
**Pull request by cornelius**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 5b4c53012c9cb426040e76181f7346ded931c789 into 16a2e65250a1b037a429f24bf1408e116a154ad3 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 5b4c53012c9cb426040e76181f7346ded931c789 into 37360ec360911842c206859d3d49c622aa670549 )

**Comment by thardeck** [comment]
lgtm

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 5b4c53012c9cb426040e76181f7346ded931c789 into 7698f264542d018ae591f7a64f49b13eee440da6 )

**Pull request merged**
