### PR TITLE
[Review] Request from 'aduffeck' @ 'SUSE/machinery/inspect_container3'

### PR DESCRIPTION
**Pull request by aduffeck**
Please review the following changes:
  * 308f2ca Add changelog entry for docker container inspection
  * 82ba9e9 Only remove the helper binary after doing the file extraction
  * 3dace33 Add DockerSystem and DockerContainer for working with docker containers
  * 0a55441 Implement "machinery inspect-container" command
  * 9ee9f43 Store the system type in the environment scope
  * 8fd169d Pass a System object to InspectTask instead of a hostname

### CODE REVIEW

**Comment by cornelius** [comment]
When running the code I get an exception during the inspection of unmanaged files:

```
Execution of "docker exec -i 23ce3c212cfcbc1289845f538eecce9508892e9479889f4825647165cb23b2b3 \[\"rpm\",\ \"-qlav\"\] \[\"sed\",\ \"s/\^\\\\\(.\\\\\)\[\^/\]\*\ /\\\\1\ /\"\]" failed with status 1: /usr/lib64/ruby/gems/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:461:in `exec': no implicit conversion of Array into String (TypeError) (...).

Error output:
/usr/lib64/ruby/gems/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:461:in `exec': no implicit conversion of Array into String (TypeError)
        from /usr/lib64/ruby/gems/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:461:in `block in fork_commands_recursive'
        from /usr/lib64/ruby/gems/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:425:in `fork'
        from /usr/lib64/ruby/gems/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:425:in `fork_commands_recursive'
        from /usr/lib64/ruby/gems/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:471:in `fork_commands'
        from /usr/lib64/ruby/gems/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:359:in `run'
        from /home/cs/suse/alfred/machinery/lib/logged_cheetah.rb:23:in `run'
        from /home/cs/suse/alfred/machinery/lib/docker_system.rb:40:in `run_command'
        from /home/cs/suse/alfred/machinery/plugins/unmanaged_files/unmanaged_files_inspector.rb:32:in `extract_rpm_database'
        from /home/cs/suse/alfred/machinery/plugins/unmanaged_files/unmanaged_files_inspector.rb:306:in `run_inspection'
        from /home/cs/suse/alfred/machinery/plugins/unmanaged_files/unmanaged_files_inspector.rb:243:in `inspect'
        from /home/cs/suse/alfred/machinery/lib/inspect_task.rb:87:in `block in build_description'
        from /home/cs/suse/alfred/machinery/lib/inspect_task.rb:79:in `each'
        from /home/cs/suse/alfred/machinery/lib/inspect_task.rb:79:in `build_description'
        from /home/cs/suse/alfred/machinery/lib/inspect_task.rb:21:in `inspect_system'
        from /home/cs/suse/alfred/machinery/lib/cli.rb:643:in `block (2 levels) in <class:Cli>'
        from /usr/lib64/ruby/gems/2.2.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
        from /usr/lib64/ruby/gems/2.2.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
        from /usr/lib64/ruby/gems/2.2.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
        from /usr/lib64/ruby/gems/2.2.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
        from /usr/lib64/ruby/gems/2.2.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
        from /usr/lib64/ruby/gems/2.2.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
        from /home/cs/suse/alfred/machinery/bin/machinery:28:in `<main>'
```

**Comment by aduffeck** [comment]
You seem to be using the traditional inspector, do you have the helper set up on that machine?

**Comment by cornelius** [comment]
I was just about to comment on that. I have the helper not set up yet. It would be good to have a more meaningful error message for this case.

**Comment by cornelius** [comment]
With the helper I get another error:

```
Errors while inspecting unmanaged-files:
 -> Could not remove file '/root/machinery-helper'.
Error: undefined method `run_command' for #<Docker::Container:0x00000001c6b370>
```

I will have to look more closely to find out what is causing this.

**Comment by aduffeck** [comment]
@cornelius the "remove file" issue should be fixed with the last commit

**Comment by cornelius** [comment]
The commit does fix the issue.

What about the services scope? It doesn't really make sense in a container, so it's a bit misleading to present that as it would run systemd.

**Comment by cornelius** [comment]
Works nicely now. I would suggest to merge this and treat the missing error message and the special handling of the services scope for containers as separate pull requests.

**Pull request merged**
