### PR TITLE
Validate export compatibility

### PR DESCRIPTION
**Pull request by cornelius**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://ci.opensuse.org/job/machinery-prophet/235637/console
If the given link has expired, you can force a Prophet rerun by just deleting this comment.
( Failure: Merged 9d8bb8cb479beddb70065edb8b8534b05104e72d into 99cd2f3abde658ee652bb2c39a4f311440cc5801 )

**Comment by cornelius** [comment]
This pull request obsoletes #548. It's a superset.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged e559e1531c559e9c0627b2998ec2c05526dc6e24 into 99cd2f3abde658ee652bb2c39a4f311440cc5801 )

**Comment by thardeck** [comment]
lgtm

**Pull request merged**
