### PR TITLE
Improve SystemDescription factory and kiwi_config_spec

### PR DESCRIPTION
**Pull request by thardeck**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 7f3386ef881fbd3b1fef26eed55ba3ff57f57900 into 5ef7ba8492b6f5ae90e6646ce6e54a52f67fe680 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged ea7e4e7feae67b2bf7dd4a821a1d0977623df266 into 5ef7ba8492b6f5ae90e6646ce6e54a52f67fe680 )

**Comment by aduffeck** [comment]
lgtm

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged be20017bf3ce60e0b7fe19c7b467b477ded112c0 into 5ef7ba8492b6f5ae90e6646ce6e54a52f67fe680 )

**Pull request closed without merging**
