### PR TITLE
Improve error message

### PR DESCRIPTION
**Pull request by mauromorales**

### CODE REVIEW

**Comment by thardeck** [comment]
Have you checked that we use single quotes everywhere else instead of double quotes?

**Comment by mauromorales** [comment]
@thardeck not everywhere but at least in this specific file we aren't. There is still issue https://github.com/SUSE/machinery/issues/1000 so we could look at that there I think.

**Comment by tgoettlicher** [comment]
lgtm

**Comment by mauromorales** [comment]
closes https://github.com/SUSE/machinery/issues/995

**Pull request merged**
