### PR TITLE
Fix html rendering (issue #598)

### PR DESCRIPTION
**Pull request by tgoettlicher**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged c1c6cc02c51e17d1eb3a3233b9813f0b955b8524 into 80511166d243670063978e103ac8f045573f96e3 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 856bf6305e4086fb448b3c95223a0a1a0274c835 into 80511166d243670063978e103ac8f045573f96e3 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 856bf6305e4086fb448b3c95223a0a1a0274c835 into 62795eb5dcafbbe53ab0c0e34ac1887cad111be6 )

**Comment by aduffeck** [comment]
Superseded by #608

**Pull request closed without merging**
