### PR TITLE
Allow gli-gem between the versions `2.11.0` and `2.13.2`

### PR DESCRIPTION
**Pull request by keberle94**

### CODE REVIEW

**Comment by cornelius** [comment]
Why between these versions?

**Comment by keberle94** [comment]
We still need version `2.11.0` because it's the latest version for SLES, but within the new leap and tumbleweed repositories there is only version `2.13.2` available. That is the reason why we tested this newer version, which worked fine.

**Comment by cornelius** [comment]
Shouldn't it just be `>= 2.11.0`?

**Comment by keberle94** [comment]
Then we would allow all higher available versions without testing, wouldn't we ?

**Comment by keberle94** [comment]
Andre suggested to have a <=2.14

**Comment by cornelius** [comment]
For many gems we assume that newer version work as well. Why would that be different for GLI?

Looking at the gem dependencies I'm actually not sure, if we have a consistent convention there. Maybe we should define one.

**Comment by aduffeck** [comment]
@keberle94 @cornelius I think it would be best to only allow patch updates in general in order to prevent issues. Those problems most likely wouldn't be caught by us our test suites but only by the users installing machinery as a gem.

**Comment by cornelius** [comment]
@aduffeck Agreed

**Comment by keberle94** [comment]
Superseded by #1464

**Pull request closed without merging**
