### PR TITLE
Changed the color of `both` link to orange

### LINKED ISSUE #1222: `both` link in `compare --html` view doesn't look like a link
The `both` link for similar details of the systems is not identifiable as link.

### PR DESCRIPTION
**Pull request by vwallfahrer**
Superseds #1224 
Fixes #1222

### CODE REVIEW

**Comment by cornelius** [comment]
I don't think this is an improvement. It makes the links stand out too much. They are not the most important links.

What problem are you trying to solve here?

**Comment by vwallfahrer** [comment]
It's not clear for the user that `both` is a link. What are your suggestions?

**Comment by aduffeck** [comment]
@cornelius What do we do about this pull request?

**Comment by cornelius** [comment]
@aduffeck Can we fix it?

**Comment by suse-tests-pass** [comment]
Prophet reports failure.
( Failure: Merged 8e6ef38f4b0356565d81ba80dd059a6537319e43 into a218099f889fe953c02100d8a6e7bef64a21ec2e )

**Comment by mschnitzer** [comment]
I think it does make much more sense here when we make the text-link to an image-link. We can use the background of https://github.com/SUSE/machinery/blob/master/html/assets/logo-os.png and replace `OS` with `both`. I think that'll look pretty good and fits to the design.

**Comment by mschnitzer** [comment]
As discussed with @cornelius: we'll close that issue. Reason: The change of the color doesn't makes it really better. We'll postpone that.

**Pull request closed without merging**
