### PR TITLE
Repositories urls in html view link to repositories

### PR DESCRIPTION
**Pull request by tgoettlicher**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 82c25a8827cc046a244d4bf4795604b82002f02d into 333011a35059c8bbcb8299d70f931adb30f4c2f9 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 82c25a8827cc046a244d4bf4795604b82002f02d into 5837eb4b77c818409e20d919310f35e217a91b09 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 82c25a8827cc046a244d4bf4795604b82002f02d into 0fcedff80dc11f696cb3236f26aae0c4fba6baaf )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 82c25a8827cc046a244d4bf4795604b82002f02d into b5378167cbc5d7dc02bc09dfedc4155d6c542f2a )

**Comment by aduffeck** [comment]
lgtm

**Pull request merged**
