### PR TITLE
[Review] Request from 'tgoettlicher' @ 'SUSE/machinery/review_150212_provide_reset_button_for_filter_in_html_view'

### PR DESCRIPTION
**Pull request by tgoettlicher**
Please review the following changes:
  * de9124b Provide reset button for filter in html view
  * 333011a Merge pull request #581 from SUSE/add_redhat_repository_support2
  * 6e9a6bd Add changelog entry for format 3 migration
  * ae9391b Optimize Migrate2to3 description
  * f6c6489 Add Red Hat inspection support to changelog
  * f2efe79 Set the package_manager attribute to zypp instead of zypper
  * 7af213c Add package_manager attribute to repository v3 schema
  * 45c9ccd Mark all other repository methods as private
  * 3a79b7e Add missing spaces
  * 2473935 Adhere to line limit
  * ecce073 Remove useless error assignment in repository inspector
  * 8e56290 Extend migration_2_to_3 integration test to new changes
  * 901caab Update test system descriptions to format v3
  * 3c09a2f upgrade_test_descriptions
  * 2ab877e Add package_manager attribute to repository test data
  * 77ed530 Filter always changing log file from unmanaged-files
  * b55db7b Don't require autorefresh and priority for repositories
  * 608a4d3 make upgrade_tests_descriptions include all libs
  * b0e742f Add packagemanger attribute to repositories
  * 192215b Switch repository renderer to factory
  * 4f3c120 Adapt repository renderer to new schema
  * 00376c1 Add YUM support to the repository inspector
  * 59c258f Add python helper script for yum repository extraction
  * 242f364 Move system double to let block in repository inspector spec
  * e1fde4c Upgrade format_version in Factory
  * d0ba9e5 Add migration to format v3
  * 179ede6 Move config-file-diffs path to analyze/config_file_diffs

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged de9124b1ded27e0f625945278bfd4f31c60cef0f into 333011a35059c8bbcb8299d70f931adb30f4c2f9 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged de9124b1ded27e0f625945278bfd4f31c60cef0f into 5837eb4b77c818409e20d919310f35e217a91b09 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged de9124b1ded27e0f625945278bfd4f31c60cef0f into 0fcedff80dc11f696cb3236f26aae0c4fba6baaf )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged de9124b1ded27e0f625945278bfd4f31c60cef0f into b5378167cbc5d7dc02bc09dfedc4155d6c542f2a )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 62a5b2bfe341bb07276045be032886607975b0cf into b5378167cbc5d7dc02bc09dfedc4155d6c542f2a )

**Comment by aduffeck** [comment]
I opened a Review-By-Refactoring PR at https://github.com/SUSE/machinery/pull/594

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 62a5b2bfe341bb07276045be032886607975b0cf into 5ce35a8b629190d5e9c742cd1b42340916de11ba )

**Pull request merged**
