### PR TITLE
Fix escaping issues in the JSON

### PR DESCRIPTION
**Pull request by tgoettlicher**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 83708461c9f129352e3524eec7389ef5053b8c24 into 62795eb5dcafbbe53ab0c0e34ac1887cad111be6 )

**Comment by aduffeck** [comment]
The comment doesn't completely match the code anymore. LGTM otherwise

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged bf9170d08371741e2797a1ee33685b63e3253d25 into 62795eb5dcafbbe53ab0c0e34ac1887cad111be6 )

**Comment by tgoettlicher** [comment]
Squashed: https://github.com/SUSE/machinery/pull/612

**Pull request closed without merging**
