### PR TITLE
Fix formatting so syntax highlighting works

### PR DESCRIPTION
**Pull request by cornelius**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged ffe4703feedf886c5aeef465fd6015a06cef73b2 into 78f97d20bdd3279abfbd7a7c32df05d3c52f3a92 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged ffe4703feedf886c5aeef465fd6015a06cef73b2 into beb797124d1f510110c3765a18b40405c0071cef )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged ffe4703feedf886c5aeef465fd6015a06cef73b2 into bfffd41f64708d7ffa147994035dd519ea5009aa )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged ffe4703feedf886c5aeef465fd6015a06cef73b2 into 5960b08e05ca243e863d7e95313d893a69f27536 )

**Comment by tgoettlicher** [comment]
LGTM

**Pull request merged**
