### PR TITLE
[Review] Request from 'aduffeck' @ 'SUSE/machinery/properly_fix_json_escaping_issues'

### PR DESCRIPTION
**Pull request by aduffeck**
Please review the following changes:
  * 58f1897 Fix escaping issues in the JSON properly
  * 856bf63 Fix style issue
  * c1c6cc0 Fix html rendering (issue #598)

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 58f18976642c8c6b9af8e3d2e107fdc91bd36ee2 into 62795eb5dcafbbe53ab0c0e34ac1887cad111be6 )

**Comment by thardeck** [comment]
lgtm

**Comment by tgoettlicher** [comment]
Having a repository with a double quote (") in the name and alias brakes the html output. Example: http://pastebin.suse.de/12782

**Comment by tgoettlicher** [comment]
Superseded by https://github.com/SUSE/machinery/pull/612

**Pull request closed without merging**
