### PR TITLE
[Review] Request from 'tgoettlicher' @ 'SUSE/machinery/review_150213_provide_tool_tips_for_service_states_in_html_view'

### PR DESCRIPTION
**Pull request by tgoettlicher**
Please review the following changes:
  * f4909bc Provide tool tips for service states in html view
  * 0fcedff Merge pull request #590 from SUSE/gracefull_fedora_repository_error
  * 0847d39 Handle missing Yum baseurls gracefully

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged f4909bc7470deffb3647dd11215d4878ec5c4ab8 into 0fcedff80dc11f696cb3236f26aae0c4fba6baaf )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged f4909bc7470deffb3647dd11215d4878ec5c4ab8 into b5378167cbc5d7dc02bc09dfedc4155d6c542f2a )

**Comment by aduffeck** [comment]
I think I'd rather apply the class to the `td` element directly and get rid of the additional `div`.

You can also simplify the code a bit by merging the classes with same titles, e.g. 

```
$("div.systemd_enabled").attr("title", 'Enabled through a symlink in .wants directory (permanently or just in /run).')
$("div.systemd_enabled-runtime").attr("title", 'Enabled through a symlink in .wants directory (permanently or just in /run).')
```

would become 

```
$("div.systemd_enabled, div.systemd_enabled-runtime").attr("title", 'Enabled through a symlink in .wants directory (permanently or just in /run).')
```

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged f4909bc7470deffb3647dd11215d4878ec5c4ab8 into 5ce35a8b629190d5e9c742cd1b42340916de11ba )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged b726657bfd9777669d53c544070f49b284932c1c into 5ce35a8b629190d5e9c742cd1b42340916de11ba )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged b726657bfd9777669d53c544070f49b284932c1c into 705c4ff52b00d00b6668e59d516c0c1d26a5e5fa )

**Comment by aduffeck** [comment]
lgtm now

**Pull request merged**
