### PR TITLE
Update copyright to 2015

### PR DESCRIPTION
**Pull request by Werni**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged fe96fe5745dc059980855031bb2293950bbd5ec0 into adb41f166e053580bc2e2a0fe5e565f6209482fb )

**Comment by thardeck** [comment]
spec/unit/scope_file_store_spec.rb needs to be adapted too

**Comment by thardeck** [comment]
and spec/data/unmanaged_files/test-quote-char.spec

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 762e23f6abb181861d01ed3c4de82f500fd58d78 into adb41f166e053580bc2e2a0fe5e565f6209482fb )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged ff1797dcd8f5a5346b42c5dc2c317c07cd104aec into adb41f166e053580bc2e2a0fe5e565f6209482fb )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged e8ddee8f60f23484e4235466c26cf8a3dc6f5885 into adb41f166e053580bc2e2a0fe5e565f6209482fb )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 9b0db5d2466c60cfe298c5a092aa978f9016b20c into adb41f166e053580bc2e2a0fe5e565f6209482fb )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 0e2b294129b5815bd47ceb8db6d64ee67c991c2a into adb41f166e053580bc2e2a0fe5e565f6209482fb )

**Comment by thardeck** [comment]
lgtm

**Pull request merged**
