### PR TITLE
Fix 596

### PR DESCRIPTION
**Pull request by thardeck**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged e16f9c01143f49081bca0a66dde6fdf521780107 into b418c745c51e142d9cd706cf5a60753b7fc2102f )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged dd4b424767034937dd56f732df63e51e087add94 into b418c745c51e142d9cd706cf5a60753b7fc2102f )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing. (Merged dd4b424767034937dd56f732df63e51e087add94 into b418c745c51e142d9cd706cf5a60753b7fc2102f)

**Comment by tgoettlicher** [comment]
LGTM

**Pull request merged**
